Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/autodl-tmp/test/feta/ICRM/ICRM/main.py", line 169, in <module>
    algorithm = algorithm_class(dataset.input_shape, dataset.num_classes, hparams)#返回一个算法实例
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/test/feta/ICRM/ICRM/algorithms.py", line 405, in __init__
    super(ICRM, self).__init__(input_shape, num_classes,
  File "/root/autodl-tmp/test/feta/ICRM/ICRM/algorithms.py", line 76, in __init__
    super(ERM, self).__init__(input_shape, num_classes,
  File "/root/autodl-tmp/test/feta/ICRM/ICRM/algorithms.py", line 43, in __init__
    self.classifier = networks.Classifier(self.featurizer.n_outputs, num_classes, self.hparams)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/test/feta/ICRM/ICRM/networks.py", line 258, in Classifier
    return GPT2Transformer(in_features, out_features, hparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/test/feta/ICRM/ICRM/networks.py", line 410, in __init__
    self.label_embed = nn.Embedding(num_classes + 1, self._backbone.config.hidden_size)
                                                     ^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'GPT2Transformer' object has no attribute '_backbone'
